var breakmasterCylinderSegments = [
  // {episode: 81, duration: 45, description: "Audio clip from The Longest Day - Not BMC"},
  {episode: 84, duration: 17, description: "Drive thru window"},
  {episode: 85, duration: 34, description: "Homecoming theme bird remix"},
  {episode: 86, duration: 32, description: "Choir director. Auld Lang Syne dog barks"},
  {episode: 87, duration: 34, description: "Car drum machine"},
  {episode: 89, duration: 45, description: "Prank call to seed store about buying beats"},
  {episode: 90, duration: 21, description: "Doing dishes Reply all Theme"},
  {episode: 91, duration: 50, description: "Reply All remix find puppy in the internet"},
  {episode: 92, duration: 79, description: "Reply All remix Yes Yes No. Jabberwocky"},
  {episode: 93, duration: 61, description: "BMC and dog record energy off distant stars."},
  {episode: 94, duration: 64, description: "Reply All remix 12x Yes, No. The internet is offensive"},
  {episode: 95, duration: 69, description: "BMC and dog travel to sad marimba planet to find music for pensive moment in a podcast"},
  {episode: 96, duration: 60, description: "In space winter's are harsh and the beat won't drop. 212 trillion miles from earth. They lose internet and are stranded"},
  {episode: 98, duration: 50, description: "Land on planet with infinitely rearrangeable beats. Like Boggle"},
  {episode: 99, duration: 95, description: "They find a piano that controls an interdimensional portal. Typing words summons that thing. cabbage, egg. Dog summons a phone with some song (?)"},
  {episode: 100, duration: 52, description: "Using the payphone Cool the dog summoned, they phone Matt Lieber"},
  {episode: 101, duration: 85, description: "They figure out the left pedal makes things appear (cabbage), the right pedal transports. Melody ending in B-E-E-B-E-E takes them to bee planet. Glowing bees in jars make music."},
  {episode: 102, duration: 85, description: "They go to planet where the air only allows one sound at a time."},
  {episode: 103, duration: 92, description: "On the same planet, Cool and BMC yell their worries into the void of space"},
  {episode: 104, duration: 86, description: "They wake up and go to icicle planet (ice, ice, baby)"},
  {episode: 105, duration: 67, description: "BMC and Cool work around monsters on Monster Planet. Blue Danube Waltz"},
  {episode: 106, duration: 73, description: "Cool plays intro from Stairway to Heaven taking them to planet where audio matches their running speed and direction"},
  {episode: 108, duration: 74, description: "Back on monster planet. Someone shoots their piano. They go hide in a cave. They play 'rock' music"},
  {episode: 109, duration: 83, description: "BMC finds a chip in a compartment in his helmet that plays notes based on location in 3D space. Apparently he and Rimsky-Korsakov put them on Bees in the late 90s (Flight of the BumbleBee). They attach it to a moth. Moths are stupid."},
  {episode: 110, duration: 88, description: "They wake up and leave the cave to find their piano has been shot up. Reference to John Cage and 4:33. They find a metal box in the piano."},
  {episode: 111, duration: 96, description: "Next morning, Cool has fixed the piano. He plays Ride of the Valkyries. They transport to just end up falling. Then Steve Bannon is chasing them. BMC wakes up to the same scene of the piano being fixed but asks Cool not to play Ride of the Valkyries."},
  {episode: 112, duration: 94, description: "They decide they need a theme song. Cool suggests Star Wars, Star Wars backwards, Star Wars starting on the dominant and inverting everything, Indiana Jones (Theme to Turkish Star Wars). They end up with the first notes of 2001, E.T., and The Golden Girls. BMC realizes he couldn't have gotten high with Rimsky-Korsakov in the 90s. It would have been 1890s"},
  {episode: 113, duration: 102, description: "They want to find out what's in the box (by dropping it from a tree) so they play ??? and end up in a jungle. Walking on the new planet plays disco beats."},
  {episode: 114, duration: 121, description: "They play ??? to go to a more disiduous forest. They want to make a new internet in the forest. bug, rock and pinecone start 'posting' as different parts of the internet. They find a rock with teeth"},
  {episode: 116, duration: 82, description: "Cool takes BMC's drum machine and make some beats with Vivaldi's Spring on top. BMC chases Cool"},
  {episode: 117, duration: 94, description: "As Cool eats a snack, BMC types D-E-C-A-F into the piano in the hopes of going to a Starbucks planet to find WiFi. BMC comes back thinking a lot of time went by while he was gone."},
  {episode: 118, duration: 105, description: "BMC throws the box trying to open it. They find some beats in the tree to bring back to podcasters. BMC finds accoustic bass strings in the piano for Cool to play. Maybe there's more on the piano they missed"},
  {episode: 121, duration: 54, description: "BMC finds a small blue switch at the bottom of the piano. They push it. "},
  {episode: 122, duration: 120, description: "They are in the bridge. Between verse and chorus. The dimension between transports. They are in all points at the same time. They go past a bunch of random planets."},
  {episode: 123, duration: 103, description: "They get stuck on the broadway musical halfstep modulation planet for a bit. The box lights up briefly when they pass through a certain location"},
  {episode: 124, duration: 116, description: "The story of planet D-E-C-A-F. BMC went looking for internet. The inhabitants gave him a chip they said would give him internet, but it just made him slower. There was a lock on his helmet that he had to pick."},
  {episode: 125, duration: 92, description: "BMC still has the slow motion chip. If Cool puts it back in BMC's helmet, he'll be able to hit the switch right when it flickers."},
  {episode: 129, duration: 122, description: "They hit the switch and end up near perilous cliffs. There are footprints. BMC finds another computer chip and decides to put it in his head. "},
];
